version: '3'

includes:
  core: ../taskfiles/Taskfile-core.yml
  uv: ../taskfiles/Taskfile-python-uv.yml
  node: ../taskfiles/Taskfile-node-npm.yml

tasks:

  lint:
    desc: "Lint code and labels"
    deps: [uv:lint]
    cmds:
      - python lint.py --dont-fix

  install:
    desc: "FIXME"
    cmds:
      - task: node:install
      - task: uv:install

  apply:
    deps: [node:sync]
    desc: "Apply labels to the current repository"
    cmds:
      - if [ "${REPO:-}" = "" ]; then {{.ECHO_FAIL}} "REPO is not set"; exit 1; fi
      - if [ "${ACCESS_TOKEN:-}" = "" ]; then {{.ECHO_FAIL}} "ACCESS_TOKEN is not set"; exit 1; fi
      - "{{.FNM}} exec github-label-sync --access-token ${ACCESS_TOKEN} --allow-added-labels --labels labels.json ${REPO}"

  clean:
    cmds:
      - task: uv:clean
      - task: node:clean

  mrproper:
    cmds:
      - task: uv:mrproper
      - task: node:mrproper
