name: renovate-non-security

on:
  schedule:
    # Runs at 01:00 UTC on the 1st day of each month
    - cron: "0 1 1 * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: renovatebot/github-action@v41.0.21
        env:
          RENOVATE_REPOSITORIES: "${{ github.repository }}"
          RENOVATE_ONBOARDING: "false"
          RENOVATE_REQUIRE_CONFIG: "ignored"
          RENOVATE_CONFIG_FILE: ".renovate-non-security.json"
          LOG_LEVEL: 'debug'
        with:
          token: ${{ secrets.MERGIFY_SYNC_TOKEN }}
