name: renovate

on:
  schedule:
    # Runs at 01:00 UTC every sunday
    - cron: "0 1 * * 0"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: renovatebot/github-action@19ba43e1bc58ed95c0ba205dee8b1bc0f27b630d # v42.0.0
        env:
          RENOVATE_REPOSITORIES: "${{ github.repository }}"
          RENOVATE_ONBOARDING: "false"
          RENOVATE_CONFIG_FILE: ".github/renovate.json"
          LOG_LEVEL: 'debug'
        with:
          token: ${{ secrets.PAT }}
